### ISSUE TITLE
Merge code into freight contrib -> MATSim-libs

### ISSUE THREAD

**Issue by kt86** [matsim-vsp/logistics#314]
- [x] move code with history
- [x] update Readme of freight contrib
- [x] create a PR
- [ ] discuss with KN
- [ ] move or recreate issues in/to MATSim-libs
- [ ] Update Readme in logistics-repo (point to freight contrib)
- [ ] make logistics-repo read-only

**Comment by rewertvsp** [comment]
Move stuff from repo logistics into the freight contrib

**Comment by rewertvsp** [comment]
> [@kainagel](https://github.com/kainagel) , [@JWJoubert](https://github.com/JWJoubert) I am now preparing this merge. The main question I have:
> 
> Should I
> 
> 1. try to keep the history or
> 2. just "copy it over, and we re-start again.. ?
> 
> Currently, I prefer 1), because the repo is not too large (my fork shows only 7MB) and we did some changes, I think it would be nice to have it in the history...

prefer 1)

**Comment by JWJoubert** [comment]
If (1) is not too involved, then sure, that would be preferred. The likelihood of actually _using_ the history is surely much lower.

**Comment by kt86** [comment]
I have now prepared a draft PR, including the history: https://github.com/matsim-org/matsim-libs/pull/3590

Will discuss this with @kainagel in our meeting on Thursday

**Comment by kt86** [comment]
New PR is: matsim-org/matsim-libs#3602
