### ISSUE TITLE
Confusion re deliveryTime for CollectionCarrier.

### ISSUE THREAD

**Issue by kt86** [matsim-vsp/logistics#334]
From @JWJoubert:
We found it a bit counter-intuitive (it took us some time to pinpoint the discrepancy) that for the LspShipment, the “collection” or pick-up time, the code uses the “delivery time”, even though the LspShipment does have a “pickupServiceTime” option.

From my first view on it, this seems to be wrong in the code, so that in https://github.com/matsim-vsp/logistics/blob/c9316926ab46b31254f24fb80ff8dc1197d8e244/src/main/java/org/matsim/freight/logistics/resourceImplementations/CollectionCarrierScheduler.java#L89 and https://github.com/matsim-vsp/logistics/blob/c9316926ab46b31254f24fb80ff8dc1197d8e244/src/main/java/org/matsim/freight/logistics/resourceImplementations/CollectionCarrierScheduler.java#L137 (?) it should use `get**Pickup**...`

Just changing the code will cause a lot of test failures (which is somehow, good, showing, that this is tested)

**Comment by JWJoubert** [comment]
> Just changing the code will cause a lot of test failures (which is somehow, good, showing, that this is tested)

Well done for many tests!

> Just changing the code...

Do you mean changing it in this one particular place only? What will be needed? A more thorough walk through the code and tracing its implications? What would your first prize be?

**Comment by JWJoubert** [comment]
@kt86, can ypu please add `XanderPENG` (GitHub username) to this project? It would be good if he gets up to speed of the developments.

**Comment by kt86** [comment]
Dear @JWJoubert , I invited him with write permissions.

**Comment by kt86** [comment]
Moved issue to https://github.com/matsim-org/matsim-libs/issues/3604
